enable: true 
accesslog: true


metrics:
  prometheus:
    addRoutersLabels: true

api:
  dashboard: true
  insecure: true

log:
    level: DEBUG
    filePath: "./traefik.log"

providers:
    file:
        filename: "./dynamic.yaml"
        watch: true

entryPoints:
    http:
        address: :8000
    db:
        address: :3306
